### ISSUE TITLE
Getting error 500. 

### ISSUE THREAD

**Issue by teebu** [xtuc/img-color-worker#6]
I wrangled and deployed your project, but it's throwing an error.

```
ReferenceError: window is not defined
    at s (worker.js:28:68973)
    at worker.js:28:70546
```

**Comment by xtuc** [comment]
It's due to a recent change in wrangler which provided a window object. You can change https://github.com/xtuc/img-color-worker/blob/master/index.js#L6 to remove window, would you mind sending a PR ?

**Comment by teebu** [comment]
I'm not sure how to fix it.

**Comment by teebu** [comment]
There seems to be other errors after this window fix.  I haven't had much success running in wrangler dev (on Windows 10). 

Only 1 image worked, others threw errors. But oddly enough deployed, it works ok. 

Seems like the local wrangler dev doesn't like something. I suspect it's base64ToArrayBuffer.

**Comment by xtuc** [comment]
what errors are you now seeing?

**Comment by teebu** [comment]
I'm not seeing any explicit errors. just "error" in the terminal and it crashes and I have to restart wrangler dev for it to load again. 

```
[2020-05-16 14:56:19] POST example.com/ HTTP/1.1 503 Service Unavailable
Uncaught (in response)
Error: internal error
```
It works for many jpgs (not all) but not for any pngs. 

Tested with these two images. Works on deployed worker, not local `wrangler dev`.

![lorewalker](https://user-images.githubusercontent.com/5531844/82131075-4e1a9c00-9786-11ea-8cf1-5f4f8b788e23.png)
![kittyeatingicecone](https://user-images.githubusercontent.com/5531844/82131099-92a63780-9786-11ea-8583-e332bc223abd.jpg)
